name: Profile Metrics

permissions:
  contents: write

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate languages metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: main
          output_action: commit

          base: ""
          template: classic
          config_timezone: Europe/Madrid

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_languages_details: percentage
